AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  authWithTwitter:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: >-
        arn:aws:iam::876243670426:role/service-role/authorizeTwitter-role-75wtfvet
      Runtime: nodejs10.x
      Timeout: 3
