version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  node:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest
commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Restore yarn dependencies
          key: cachev21-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          working_directory: ~/workspace

  save_yarn:
    steps:
      - save_cache:
          name: Cache yarn dependencies
          key: cachev21-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules
          working_directory: ~/workspace
jobs:
  setup:
    executor:
      name: node
    steps:
      - checkout
      - restore_yarn
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
  lint:
    executor:
      name: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run lint
          command: yarn run lint
  unit:
    executor:
      name: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit
          command: yarn run test:unit
workflows:
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - unit:
          requires:
            - setup
      - cypress/install:
          yarn: true
          build: 'yarn run build'
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          command: 'yarn run test:e2e' # Run all tests(Do not write cypress/run)
